### ISSUE TITLE
Please provide an iOS case demo on how to use the plugin.

### ISSUE THREAD

**Issue by OmgKevin** [mfdeveloper/cordova-plugin-nativeview#15]
Hello, can you provide a copy of iOS xcode case, how to use this plugin to get from JS to native and return to JS from the original, because I am learning new Cordova,Just looking at the instructions will make it very difficult to understand. thank you very much

**Comment by OmgKevin** [comment]
Because I tried to understand the underlying logic of the plugin, your approach is to use the [self.viewController.navigationController pushViewController: animated:YES]; in the cordova plugin to complete the jump to native. I did this before I touched the plugin: [self.viewController presentViewController:testViewCtrl animated:YES completion:^{ }]; It is also possible to jump to the iOS native page. But the problem I came across is that when I use the [self.navigationController popViewControllerAnimated:YES]; in the iOS native interface through the navigation bar self.navigationItem.leftBarButtonItem, it can't be implemented to return to the HTML page, so This is bothering me how can I handle it? PS: I recreated the new UINavigationController before JS entered iOS natively: 
ChatViewController *vc = [[IMAChatViewController alloc] initWith:user];
UINavigationController *chatNav = [[UINavigationController alloc] initWithRootViewController:vc];
self.viewController.view.window.rootViewController = chatNav;

**Comment by OmgKevin** [comment]
Because I tried to understand the underlying logic of the plugin, your approach is to use the [self.viewController.navigationController pushViewController: animated:YES]; in the cordova plugin to complete the jump to native. I did this before I touched the plugin: [self.viewController presentViewController:testViewCtrl animated:YES completion:^{ }]; It is also possible to jump to the iOS native page. But the problem I came across is that when I use the [self.navigationController popViewControllerAnimated:YES]; in the iOS native interface through the navigation bar self.navigationItem.leftBarButtonItem, it can't be implemented to return to the HTML page, so This is bothering me how can I handle it?

 PS: I recreated the new UINavigationController before JS entered iOS natively:

ChatViewController *vc = [[IMAChatViewController alloc] initWith:user];
UINavigationController *chatNav = [[UINavigationController alloc] initWithRootViewController:vc];
self.viewController.view.window.rootViewController = chatNav;

Thank you, look forward to hearing from you.   ：）

**Comment by OmgKevin** [comment]
Because I tried to understand the underlying logic of the plugin, your approach is to use the [self.viewController.navigationController pushViewController: animated:YES]; in the cordova plugin to complete the jump to native. 
I handled this before I touched the plugin you wrote: [self.viewController presentViewController:  animated:YES completion:^ {}]; This can be done to jump to the iOS native interface, but when I am native on iOS In the interface, when you want to click the button event to execute the [self.navigationController popViewControllerAnimated:YES]; method, it can't return to the HTML page, and there is no reaction at all, so this question plagues me what should I do?

PS:  I recreated the new UINavigationController before JS entered iOS natively，to reach the iOS native interface that will be entered with a navigation:

ChatViewController *vc = [[MyChatViewController alloc] init];
UINavigationController *chatNav = [[UINavigationController alloc] initWithRootViewController:vc];
self.viewController.view.window.rootViewController = chatNav;

Thank you, look forward to hearing from you. ：）

**Comment by OmgKevin** [comment]
Hello, I wrote a plugin myself. The main logic is to jump from the JS page to the iOS native page. I use [self.viewController.navigationController pushViewController:vc animated:YES]; this is achievable in my case. But the iOS native page I entered is required to have a UINavigationController, so I define it myself. This caused the problem to be that I can't return to the JS page by clicking the left navigation bar and returning to the popviewcontorller from the iOS native page, requesting your help.

**Comment by mfdeveloper** [comment]
Hi @OmgKevin !! Sorry for my late response. I was traveling and arrived today at my city. I will check your e-mail about this, download your example project, and I will try help you. Probablly tomorrow, ok?

Anyway, thank you so much for submit this doubt :)

**Comment by OmgKevin** [comment]
> Hi @OmgKevin !! Sorry for my late response. I was traveling and arrived today at my city. I will check your e-mail about this, download your example project, and I will try help you. Probablly tomorrow, ok?
> 
> Anyway, thank you so much for submit this doubt :)

Wow, I am sorry to bother you. We were sometimes poor on both sides, and the difference was 11 hours, so I only saw your reply. Thank you very much, I am willing to wait slowly

**Comment by OmgKevin** [comment]
> Hi @OmgKevin !! Sorry for my late response. I was traveling and arrived today at my city. I will check your e-mail about this, download your example project, and I will try help you. Probablly tomorrow, ok?
> 
> Anyway, thank you so much for submit this doubt :)

Thank you very much and look forward to hearing from you soon.
