### ISSUE TITLE
Does not open view controller

### ISSUE THREAD

**Issue by amitanmol** [mfdeveloper/cordova-plugin-nativeview#16]
I am using latest plugin version 1.0.10 and trying to open Login view controller on button click of cordova view but it does not work.

cordova.plugins.NativeView.show({storyboardName: 'Main', viewControllerName: 'LoginViewController'});

**Comment by ffalcinelli** [comment]
Try to use the 'Storyboard ID' value configured in the storyboard for your controller, and use it as 'viewControllerName', in my case they're different (e.g. my controller is 'ConfigurationController' whereas the storyboard ID is just 'Config')

**Comment by amitanmol** [comment]
'LoginViewController' is storyboard ID. I have done the same as you are suggesting and as per documentation but it does not open login view controller. 

I dig a deep and found that it calls '- (void) instantiateViewController:(NSString *)viewControllerName fromStoryboard:(NSString *)storyboardName' function in 'CDVNativeView.m' file. And the problem is with '[self.viewController.navigationController pushViewController:destinyViewController animated:YES];' code. It doesn't push but if I replace with '[self.viewController presentViewController:destinyViewController animated:YES completion:nil];' then it works.

I am using Xcode 10.0 and latest plugin.

**Comment by NghiTranVNS** [comment]
> 'LoginViewController' is storyboard ID. I have done the same as you are suggesting and as per documentation but it does not open login view controller.
> 
> I dig a deep and found that it calls '- (void) instantiateViewController:(NSString *)viewControllerName fromStoryboard:(NSString *)storyboardName' function in 'CDVNativeView.m' file. And the problem is with '[self.viewController.navigationController pushViewController:destinyViewController animated:YES];' code. It doesn't push but if I replace with '[self.viewController presentViewController:destinyViewController animated:YES completion:nil];' then it works.
> 
> I am using Xcode 10.0 and latest plugin.

Hello @amitanmol : I got same with your issues. I don't know how to fix it with your solution still. Could you please describe the detail to fix it?

**Comment by u2jrmw** [comment]
> 'LoginViewController' is storyboard ID. I have done the same as you are suggesting and as per documentation but it does not open login view controller.
> 
> I dig a deep and found that it calls '- (void) instantiateViewController:(NSString *)viewControllerName fromStoryboard:(NSString *)storyboardName' function in 'CDVNativeView.m' file. And the problem is with '[self.viewController.navigationController pushViewController:destinyViewController animated:YES];' code. It doesn't push but if I replace with '[self.viewController presentViewController:destinyViewController animated:YES completion:nil];' then it works.
> 
> I am using Xcode 10.0 and latest plugin.

Dude you are a hero, I would have never figured that out.

**Comment by amitanmol** [comment]
Thanks @u2jrmw

**Comment by u2jrmw** [comment]
@amitanmol A little off topic, but you seem to have a good handle on this. Is it possible to pass a value back from the viewController code into Ionic. I can dismiss the launched page just fine, but I can't figure out a way to send a value back. I am concerned that because the plugin launches the native view that at that point it loses the bridge between Ionic and native and the typical callback methods wouldn't work. Any pointers?

**Comment by amitanmol** [comment]
Hi @u2jrmw, sorry for late reply. No, I have not handle such condition. It's an interesting topic, I will try.

**Comment by u2jrmw** [comment]
I figured it out and was able to pass a value back using the dom manipulation of the webview. I'd have to go back to my code to see exactly what I did.

**Comment by amitanmol** [comment]
Great! I thik you should share what needs to do in the code so every one can be beneficial.

**Comment by mfdeveloper** [comment]
Hello guys!!

I'm so sorry for soooo late responde. My work made me crazy with a lot of new features and I've focused in another cordova plugin updates :(

So, Finally the PR #18 was merged. With them, I've create a **IONIC** example project that uses this plugin. Still needs some improvements, that I will be add in the next weeks.

@u2jrmw The `IOS` bug was fixed and merged into branch **[master]**. I will publish a new release to **npm** during the next week 😄

**Comment by gghangura** [comment]
Hey guys, this does not work for me. Can somebody help me?

I also tried to use 1.0.11 but doesnt work. There is no error generated in the console.

**Comment by klemensz** [comment]
I installed the latest version using `cordova plugin add cordova-plugin-nativeview --save` but it still seems to have the old code (`pushViewController`)? Nothing happens when calling .show(). How can I install the latest code? Do I manually have to add it to the Pod file? But I suppose this will get overwritten, so I would like to avoid that.
