### ISSUE TITLE
Ionic - plugin usage

### ISSUE THREAD

**Issue by LucasBourgeois** [mfdeveloper/cordova-plugin-nativeview#17]
Hi there, 

I'm using Ionic 4 and TS on my project, and I'm struggling to use cordova plugins that are not able to be imported.

In my ts file, i tried : 
window.cordova.plugins.NativeView() .. and typo variants, w/wo window etc.

Can you explain me how to use your plugin in Ionic ? 

Thanks in advance.
Lucas

**Comment by RichardBoyder** [comment]
Hi guys I'm trying to also use this in ionic... and it sais:
 Property 'NativeView' does not exist on type 'CordovaPlugins'.

How do i import the plugin into the typescript ionic page?

**Comment by mfdeveloper** [comment]
Hello @RichardBoyder and @LucasBourgeois !!

I'm creating a `.d.ts` file to use this plugin with `Typescript` autocomplete. Sadly, the file that I've merged in **[master]** branch, works in _VSCode_, but emits an compile error in Angular/IONIC projects.

I'm creating a `@types/cordova-plugin-nativeview` package. When finished and working, I will post another commet here 😄 

For while, you can use this plugin like `JS` using a **any** type cast. You can do something like this:

```typescript
(cordova.plugins as any).NativeView.show(...);
```

A example project called [ionic-example](https://github.com/mfdeveloper/cordova-plugin-nativeview/tree/master/ionic-example) was created!

**Comment by RichardBoyder** [comment]
Thankyou sir 👌. Will take a look.

**Comment by mfdeveloper** [comment]
Hello @RichardBoyder !!

I think that you can use the example project and it's ok for you, right? I'm closing this issue now, ok?

If you have any trouble, please, keep me in touch 😄
