### ISSUE TITLE
this plugin doesn't work for me

### ISSUE THREAD

**Issue by gghangura** [mfdeveloper/cordova-plugin-nativeview#22]
Hey guys, this does not work for me. Can somebody help me?

I also tried to use 1.0.11 but doesnt work. There is no error generated in the console.

_Originally posted by @gghangura in https://github.com/mfdeveloper/cordova-plugin-nativeview/issues/16#issuecomment-579049679_

**Comment by mfdeveloper** [comment]
Hello @gghangura !

I updated the issue #16 with the latest version of this plugin. Please, update to version `1.0.12` and try again. If have any problems after that, please post your code snippet here or upload a example project for me, ok?
