### ISSUE TITLE
Trying to access created view in Java

### ISSUE THREAD

**Issue by ajmeese7** [mfdeveloper/cordova-plugin-nativeview#23]
Hey there. I'm not sure if what I'm trying to use this plugin for is what it's intended to do, so I'm double checking as I've had no success this far.

My goal is to create a View in the Java of my Android Cordova plugin because I need one to modify `setImportantForAccessibility`. I'm running the suggested code snipped to show a view, but I don't know how I would access that in my Java code to run `View` functions on it.

Any ideas, or do you know if that is possible with this plugin?

**Comment by mfdeveloper** [comment]
Hello  @ajmeese7 ! How are you nowdays?

So, I'm closing this issue now ok? However, let me know whether you solved this problem, right?
