### ISSUE TITLE
property NativeView does not exist on type window

### ISSUE THREAD

**Issue by matsyoman** [mfdeveloper/cordova-plugin-nativeview#3]
Hello,

I get this message when I try to use your plugin, where do I need to add the line of code? And do I have to include the plugin, I have tried it but its not a method?

thank you in advance

**Comment by mfdeveloper** [comment]
Hi @matsyoman !!

I saw that you've closed this issue. I imagine that you could use this plugin.

Anyway, I did some updates yesterday/today to use this plugin. Please, see the PR #5 and give me a feedback on your another issue #3

**Comment by matsyoman** [comment]
hi,

I had a problem but it is solved! thnx for updating, I gonna take a look at it!
