### ISSUE TITLE
going back to ionic app (iOs)

### ISSUE THREAD

**Issue by matsyoman** [mfdeveloper/cordova-plugin-nativeview#4]
How can you go back to the ionic/cordova app on iOs?

**Comment by mfdeveloper** [comment]
Hello @matsyoman ! I'm so sorry about my late response...my job is a madness at the last days :cry: 

So, you can do something like this:

```js
// Don't pass parameters
cordova.plugins.NativeView.show();
```
On **IOS** only, will be verified if exists a `NavigationController` on your project and try execute `[popWithAnination: Yes]` method. If your IOS project don't contains a NavController, will be raised an exception.

On the next releases, I will create a `cordova.plugins.NativeView.back()` method, to more "readable" and more concise action.

Please, see the PR #5 for detailed changes that I did yesterday. You can see the too the [README.md](https://github.com/mfdeveloper/cordova-plugin-nativeview/blob/master/README.md) file. It was updated with latest changes!

Thank you so much for your issue!! :smile:

**Comment by matsyoman** [comment]
Thnx for helping!

**Comment by mfdeveloper** [comment]
@matsyoman Can you close this issue by now?
