### ISSUE TITLE
Closing the Native View

### ISSUE THREAD

**Issue by krishnaclouds** [mfdeveloper/cordova-plugin-nativeview#7]
Is there a way to close the Native view (ios) and going back to Cordova.

**Comment by krishnaclouds** [comment]
Hey, I found the solution. Cheers. Thanks for the help. 

I used popViewController functionality!!

**Comment by mfdeveloper** [comment]
Hello @OmgKevin !

Can you describe your problem in details and/or paste stack trace error or a print screen? You can inspect the webview in a IOS device using **Safari**.

Anyway, I'm using the latest version `1.0.9` and I couldn't see this problem.

**Comment by OmgKevin** [comment]
> Hello @OmgKevin !
> 
> Can you describe your problem in details and/or paste stack trace error or a print screen? You can inspect the webview in a IOS device using **Safari**.
> 
> Anyway, I'm using the latest version `1.0.9` and I couldn't see this problem.

Thank you for finally replying to my question. I sent you an email. Have you read it? Just how to return an iOS native page with a UINavigationController to a JS page.
